spring:
  application:
    name: config
  config:
    import: "optional:configserver:http://localhost:8085"
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: refresh