# docker compose up -d    # Run All the compose file background
# docker compose down     # Stop all container
services:
  postgres:
    container_name: local_postgres
    image: postgres:18.4-alpine
    environment:
      POSTGRES_USER: argroy
      POSTGRES_PASSWORD: Papai12#
      PGDATA: /data/postgres
      PGTZ: Asia/Kolkata
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_ui
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  mongo:
    image: mongo:7.0
    container_name: local_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_admin
      MONGO_INITDB_ROOT_PASSWORD: root_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network
    restart: always
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_ui
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root_password
      ME_CONFIG_BASICAUTH_USERNAME: web_user
      ME_CONFIG_BASICAUTH_PASSWORD: web_password
    ports:
      - "8090:8081"
    depends_on:
      - mongo
    networks:
      - mongo_network
    restart: always

networks:
  postgres:
    driver: bridge
  mongo_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo_data: