server:
  port: 8085
spring:
  application:
    name: EComConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration_data
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"