server:
  port: 8082
spring:
  application:
    name: product
  datasource:
    url: "jdbc:postgresql://ep-little-cherry-apzpafux-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require"
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASS}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect